- name: Install Python (RedHat)
  become: true
  yum:
    name: python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Python (Debian)
  apt:
    name: python3-pip
    state: present
  when: ansible_os_family == "Debian"
